name: "wb-analytic-bot"
version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      BOT_TOKEN: 6776917438:AAGlUDgFhyeSp3PfDK1PRYT73QH41aoXnNI
      MONGO_HOST: mongo
      MONGO_PORT: 27017
    networks:
      - database
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    networks:
      - database

networks:
  database:

volumes:
  mongo-data:
